Repository rancher-sandbox/cluster-api-provider-harvester, pull requests merged in 2024-11, with the labels that each got.

#73 fixed RFC1035 naming for generated names and fixed some linting issues
  controllers/harvestercluster_controller.go
  util/ippool.go
  util/util.go
  util/util_test.go
Labels: kind/bug, size/m

#72 fix: update the RKE2 worker machine templates to use the correct RKE2 version
  templates/cluster-template-rke2-dhcp.yaml
  templates/cluster-template-rke2.yaml
Labels: kind/bug, size/xs

#86 Implement a process to discharge the user from generating cloud provider configuration
  Makefile
  api/v1alpha1/harvestercluster_types.go
  api/v1alpha1/harvestermachine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_harvesterclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_harvestermachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_harvestermachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_infraclustertemplates.yaml
  config/rbac/role.yaml
  controllers/harvestercluster_controller.go
  controllers/harvestercluster_controller_test.go
  controllers/harvestermachine_controller.go
  go.mod
  pkg/clientset/versioned/clientset.go
  pkg/clientset/versioned/fake/clientset_generated.go
  util/cloud_provider.go
  util/cloud_provider_test.go
  util/util.go
Labels: kind/feature, size/xl

#82 fix: upgrade longhorn csi sidecars version
  templates/cluster-template-rke2-dhcp.yaml
  templates/cluster-template-rke2.yaml
Labels: size/s, kind/bump
