Repository rancher-sandbox/cluster-api-provider-harvester, pull requests merged in 2024-06, with the labels that each got.

#34 [WIP] kind/documentation: Updating Readme according to the issue #33
  README.md
Labels: size/s, kind/bug

#45 kind/feature: Adding new clusterctl generate cmd
  README.md
Labels: size/s, kind/bug

#47 kind:feature : Bumping various longhorn and harvester versions
  templates/cluster-template-rke2.yaml
Labels: kind/feature

#42 Update deps
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  go.mod
Labels: kind/feature, kind/bump
